### ISSUE TITLE
kosmtik and openstreetmap-carto rendering without osm-polygons and land polygons

### ISSUE THREAD

**Issue by superrache** [Ircama/osm-carto-tutorials#12]
I just followed your tutorial to configure a debian VM embedding kosmtik and the openstreetmap-carto style, and another machine containing the PostGIS database.

It's now working well except that the map I get is blue:
![image](https://user-images.githubusercontent.com/4458770/46145533-b2f74a80-c260-11e8-873c-d6e15a7a3b1b.png)
It looks like two elements are missing: 
- every OSM polygons from database, such as building, landuse, ...
- the land polygon from shapefiles

However, osm points and polylines work well. And I downloaded shapefiles data using the get-shapefiles script to download them in the /openstreetmap-carto/data folder.

In kosmtik log, I don't have any error, but a long list of warnings like:
```
Warning: shapefile.mss:22:6 line-offset is unstable. It may change in the future.
Warning: landcover.mss:591:4 line-offset is unstable. It may change in the future.
```
And also:
```
Warning: landcover.mss:570:6 Styles do not match layer selector #landcover
```
I have seen this issue: https://github.com/gravitystorm/openstreetmap-carto/issues/2101
but the problem seems to be solved.

Any idea on what I'm doing wrong?

**Comment by Ircama** [comment]
Please try downgrading *carto* to version *0.18.2* instead of *1.1.0*.

```shell
sudo npm install -g carto@0
```

**Comment by superrache** [comment]
I finally found that my PostGIS planet_osm_polygon was empty due to an osm2pgsql problem. By choosing a smaller dataset on GeoFabrik, I can get working the polygons.
