### ISSUE TITLE
Problem with "get-shapefiles.py"

### ISSUE THREAD

**Issue by zsoooc** [Ircama/osm-carto-tutorials#17]
Hi!

Thank you for this very useful and well detailed tutorial!

Unfortunately, I got a problem at the "Create data folder" stage. I cloned successfully the openstreetmap-carto with this command: "git clone https://github.com/gravitys..."
I have to download the shape files using the "get-shapefiles.py" script. However, this file does not exist in the script folder. But there is a "get-external-data.py" file. I tried this, but I says the "external-data.yml" is missing.
Do you have any suggestions how to solve this issue?

**Comment by Ircama** [comment]
Yes, you are right.
I need to find time to update the tutorials according to the new openstreetmap-carto version.

**Comment by Ircama** [comment]
Documentation updated.
