### ISSUE TITLE
Building kosmtik failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by matthijsmelissen** [Ircama/osm-carto-tutorials#3]
On 16.04, building Kosmtik seems to fail. I get the following error:

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mapnik@3.5.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mapnik@3.5.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matthijs/kosmtik/npm-debug.log

This is also discussed at https://github.com/kosmtik/kosmtik/issues/155 and https://github.com/mapnik/node-mapnik/issues/660.

Am I correct in assuming that this manual is intended for Ubuntu 14.04?

**Comment by Ircama** [comment]
I think you might have an issue with your version of nodejs. Would you try this and do again the installation?

```
sudo apt-get install nodejs-legacy
```

**Comment by matthijsmelissen** [comment]
Thanks, with nodejs-legacy it works indeed. Do you know when to use the legacy package? Is this for 16.04? Perhaps also something to include in the documentation.

**Comment by Ircama** [comment]
I think this problem might also happen with other O.S. versions; it looks like Kosmtik needs an old nodejs at the moment. I have just tested the latest v7 beta downloaded from [Github](https://github.com/nodejs) on Ubuntu 16.04, which fails.

Just report the instructions to compile it (will not support the installation of Kosmtik):

```
cd /tmp
sudo apt-get install g++ make cmake
git clone https://github.com/nodejs/node.git
cd node
./configure && make && sudo make install

# To remove the sources:
cd ../..
rm -rf /tmp/node
```

I'll update the documentation.
