### ISSUE TITLE
YAML for python is missing

### ISSUE THREAD

**Issue by matthijsmelissen** [Ircama/osm-carto-tutorials#5]
YAML for Python is missing on the page 'Installing Kosmtik and OpenStreetMap-Carto on Ubuntu'. This is necessary in order to run scripts/indexes.

It can be installed with

```
sudo apt-get install python-yaml
```

or the relevant pip command.

**Comment by Ircama** [comment]
@math1985: very appreciated feedback, thanks! Will update doc asap
