### ISSUE TITLE
Ubuntu Tileserver Tutorial - Carto error when processing project.mml

### ISSUE THREAD

**Issue by glen442** [Ircama/osm-carto-tutorials#7]
Ive been following the Ubuntu (16.04) Tile Server Tutorial. 
I am using Ubuntu 16.04.1

When I get to [this](https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/#install-carto-and-build-the-mapnik-xml-stylesheet) section,  the line: 
`carto -a "3.0.0" project.mml > style.xml` 

exits with:  
`carto: Unexpected token s`

Output of carto -v
`carto 0.9.5 (Carto map stylesheet compiler)`
Which is the latest version in the repos.

I have used an online yaml validator to validate project.mml.

project.mml (cloned from github) begins with the line:
`scale: 1`

Which indicates carto might be erroring on the first character. However, there is no line number in the error.

Any suggestions?

**Comment by Ircama** [comment]
Thanks for signaling this issue.

You need the latest carto version

I’m afraid I have to check the carto install procedure to ensure that the latest carto version is used, which is currently [0.16.3](https://github.com/mapbox/carto/releases/tag/v0.16.3).

```
carto -v
carto 0.16.3 (Carto map stylesheet compiler)
```

I meanwhile updated the documentation. I’ll better check this as soon as I have enough time.

If you issued

    sudo apt-get update
    sudo apt-get -y upgrade
    sudo apt-get install -y node-carto

we need to understand why the latest version was not installed.

**Comment by glen442** [comment]
Thanks for the reply,

Just to confirm - output of:
`lsb_release -a`
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```
```
glen@osm:~$ sudo apt-get update
Hit:1 http://gb.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:3 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://gb.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Fetched 306 kB in 0s (323 kB/s)
Reading package lists... Done
```
```
glen@osm:~$ sudo apt-get -y upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  snapd ubuntu-core-launcher
0 to upgrade, 0 to newly install, 0 to remove and 2 not to upgrade.
```
```
glen@osm:~$ sudo apt-get install -y node-carto
Reading package lists... Done
Building dependency tree
Reading state information... Done
node-carto is already the newest version (0.9.5-2).
0 to upgrade, 0 to newly install, 0 to remove and 2 not to upgrade.
```
```
glen@osm:~$ carto -v
carto 0.9.5 (Carto map stylesheet compiler)
```

Meanwhile I'm investigating backports.

**Comment by glen442** [comment]
Update:

It looks like 0.9.5-2 is the latest version in _any_ of the repos - including zesty.

Package search [here](http://packages.ubuntu.com/search?keywords=node-carto&searchon=names&suite=all&section=all)

**Comment by ImreSamu** [comment]
As I know, the
 `npm install -g @mapbox/carto`  
command is the suggested way to install, see https://github.com/mapbox/carto

**Comment by glen442** [comment]
After copious googling: 

Removed the repo version:
`sudo apt-get remove node-carto`

Installed npm:
`sudo apt-get install npm`

when installing npm from repos, it installs node as 'nodejs'.

Fixed with:
`sudo ln -s /usr/bin/nodejs /usr/bin/node`

The symlink is included in the package nodejs-legacy
`apt-get install nodejs-legacy` 

It's worth mentioning that either of these fixes will conflict with the 'node' package (which seems to be an Amateur Packet Radio Node program). Also, I'm not sure how the symlink will interract with n**v**m installs. The node toolchain is not my strong suit.


full installation:
```
sudo apt-get install -y npm
sudo ln -s /usr/bin/nodejs /usr/bin/node
npm install -g @mapbox/carto
npm install -g millstone
```

Is millstone required? I included it anyway as the doc suggests it helps "localizing external resources".

Finally:
```
glen@osm:~$ carto -v
carto 0.16.3 (Carto map stylesheet compiler)
```

**Comment by Ircama** [comment]
Thanks for all notes. I think that to properly install the latest version of node-carto the following procedure should be valid:

    sudo apt install -y nodejs-legacy
    sudo apt install -y npm
    sudo npm install -g @mapbox/carto

It should replace the current [carto installation procedure](https://github.com/Ircama/osm-carto-tutorials/blame/eec9c8ddac5ed2ac130ec1c9810dda2f6eb5e13e/pages/36_tile-server-ubuntu.md#L80-L82).

I am performing some testings before updating the configuration.
