### ISSUE TITLE
"checkpoint_segments" is no longer a valid configuration setting in 9.5+

### ISSUE THREAD

**Issue by sedenardi** [Ircama/osm-carto-tutorials#9]
Using the `checkpoint_segments` in `postgresql.conf` will cause the server to fail next time it is loaded. The settings `min_wal_size` and `max_wal_size` should now be used to tune the size of the transaction log.

http://www.databasesoup.com/2016/01/configuration-changes-in-95-transaction.html

**Comment by Ircama** [comment]
Thanks for reporting this.

I am updating the related tuning description with the following.

The PostgreSQL tuning adopted by OpenStreetMap can be found in the [PostgreSQL Chef Cookbook](https://github.com/openstreetmap/chef/blob/master/cookbooks/postgresql/attributes/default.rb): the specific PostgreSQL tuning for the OpenStreetMap tile servers is reported in the related [Tileserver Chef configuration](https://github.com/openstreetmap/chef/blob/master/roles/tile.rb#L38-L45).

For a dev&test installation on a system with 16GB of RAM, the suggested settings are the following:

    shared_buffers = 2GB
    work_mem = 128MB
    maintenance_work_mem = 1GB
    wal_level = minimal
    synchronous_commit = off
    min_wal_size = 1GB
    max_wal_size = 2GB
    checkpoint_timeout = 15min
    checkpoint_completion_target = 0.9
    default_statistics_target = 1000
    autovacuum = off
    fsync = off

**Comment by sedenardi** [comment]
Great, thank you.
